name: microclimate-vision
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.28
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.6
  - aws-c-s3=0.6.6
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - blas=1.0
  - blosc=1.21.6
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - cfitsio=4.4.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - contextily=1.6.2
  - contourpy=1.3.0
  - cpython=3.12.6
  - cuda-cccl=12.6.37
  - cuda-cccl_win-64=12.6.37
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.68
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cycler=0.12.1
  - debugpy=1.8.6
  - decorator=5.1.1
  - double-conversion=3.3.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - filelock=3.16.1
  - fmt=11.0.2
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.54.1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.9.2
  - geographiclib=2.0
  - geojson=3.1.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geopy=2.4.1
  - geos=3.12.2
  - geotiff=1.7.3
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kealib=1.5.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.68
  - libcurand-dev=10.3.7.68
  - libcurl=8.10.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.21
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgdal=3.9.2
  - libgdal-core=3.9.2
  - libgdal-fits=3.9.2
  - libgdal-grib=3.9.2
  - libgdal-hdf4=3.9.2
  - libgdal-hdf5=3.9.2
  - libgdal-jp2openjpeg=3.9.2
  - libgdal-kea=3.9.2
  - libgdal-netcdf=3.9.2
  - libgdal-pdf=3.9.2
  - libgdal-pg=3.9.2
  - libgdal-postgisraster=3.9.2
  - libgdal-tiledb=3.9.2
  - libgdal-xls=3.9.2
  - libglib=2.80.3
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.65.5
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.44
  - libpq=16.4
  - libprotobuf=5.27.5
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.11.1
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.8.1
  - markupsafe=2.1.5
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - minizip=4.0.6
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numpy=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.4
  - platformdirs=4.3.6
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - proj=9.5.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyogrio=0.9.0
  - pyparsing=3.1.4
  - pyproj=3.6.1
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.12.6
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=306
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt6-main=6.7.2
  - rasterio=1.3.11
  - re2=2023.09.01
  - requests=2.32.3
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - shapely=2.0.6
  - six=1.16.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - spdlog=1.14.1
  - sqlite=3.46.1
  - stack_data=0.6.2
  - statsmodels=0.14.3
  - sympy=1.13.2
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tiledb=2.26.1
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uriparser=0.9.8
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - fastjsonschema==2.20.0
      - h3==3.7.7
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - nbformat==5.10.4
      - nbstripout==0.7.1
      - referencing==0.35.1
      - rpds-py==0.20.0
      - torchaudio==2.4.1
      - torchvision==0.19.1
