"cnn_architecture": "resnet18"
"cnn_feature_dim": 128
"cnn_layernorm": true
"cnn_subtract": false
"dataset_basename": "clearsky_panosate_AH"
"dataset_name_s": "ref_sequence_AH_NUS"
"dataset_root": "./data/processed"
"dataset_standard": "train"
"debug": false
"device": "cuda"
"dropwss": ["WS_03", "WS_13"]
"eval_batch_size": 128
"input_scaling": true
"input_weather": ["air tem", "RH", "wind speed", "solar radiation"]
"log_root": "./logs/test5"
"loss_function": "MSE"
"lr_factor": 0.1
"lr_initial": 0.0001
"lr_monitor": "test_loss"
"lr_patience": 10
"lr_patience_es": 3
"lstm_dropout_ratio": 0.1
"lstm_ft_map_size": 8
"lstm_hidden_units": 256
"lstm_input_size": 4
"lstm_layernorm": true
"lstm_num_layers": 4
"lstm_sequence_length": 24
"lstm_zero_init": true
"min_lr": 1.0e-07
"model": "MCVisionNet_panosate_v2"
"momentum": 0.9
"n_gpu": 1
"num_workers": 1
"numerical_inputs": ["air tem", "RH", "wind speed", "solar radiation"]
"optimizer": "Adam"
"output_scaling": true
"pano_folder": "./data/processed/panorama/fixposi_128_256"
"pano_map_folder": "./data/processed/pano_map_128_256"
"pano_x": 256
"pano_y": 128
"regressor_dropout_ratio": 0.0
"sate_folder": "./data/processed/satellite/mapbox_128_256"
"sate_x": 256
"sate_y": 128
"save_interval": 50
"scaling_type": "standard"
"scheduler": "ReduceLROnPlateau"
"seed": 2020
"tag": "clearsky_panosate_128_256_tune_input"
"target_weather": "air tem"
"test_type": "test2"
"train_batch_size": 128
"train_max_epochs": 100
"tune_hyperparameters": true
"wandb": true
"wandb_project": "mcvision_tune_5"
"weight_decay": 0.0001
