"cnn_architecture": "resnet18"
"cnn_feature_dim": 128
"cnn_layernorm": true
"cnn_subtract": false
"training_data_path": "data/microclimate/training_sample.csv"
"validation_data_path": "data/microclimate/validation_sample.csv"
"test_data_path": "data/microclimate/test_sample.csv"
"sequence_data_path": "data/microclimate/sequence_sample.csv"
"dataset_standard": "train"
"debug": false
"device": "cuda"
"eval_batch_size": 128
"input_scaling": true
"input_weather": ["air tem", "RH", "wind speed", "solar radiation"]
"log_dir": "./logs/test"
"loss_function": "MSE"
"lr_factor": 0.1
"lr_initial": 0.0001
"lr_monitor": "test_loss"
"lr_patience": 10
"lr_patience_es": 3
"lstm_dropout_ratio": 0.1
"lstm_ft_map_size": 8
"lstm_hidden_units": 256
"lstm_input_size": 4
"lstm_layernorm": true
"lstm_num_layers": 4
"lstm_sequence_length": 24
"lstm_zero_init": true
"min_lr": 1.0e-07
"model": "MCVisionNet_sate"
"momentum": 0.9
"n_gpu": 1
"num_workers": 1
"numerical_inputs": ["air tem", "RH", "wind speed", "solar radiation"]
"optimizer": "Adam"
"output_scaling": true
"pano_folder": "./data/panorama"
"pano_map_folder": "./data/panorama"
"pano_x": 256
"pano_y": 128
"regressor_dropout_ratio": 0.0
"sate_folder": "./data/satellite"
"sate_x": 128
"sate_y": 128
"save_interval": 50
"scaling_type": "standard"
"scheduler": "ReduceLROnPlateau"
"seed": 2020
"tag": "sample"
"target_weather": "air tem"
"train_batch_size": 128
"train_max_epochs": 100
"tune_hyperparameters": true
"wandb": true
"wandb_project": "mcvision_tune_5"
"weight_decay": 0.0001
